version: '3.8'

services:
  qiankun-app:
    container_name: qiankun
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8888}:8888"
    volumes:
      - ./ssl:/etc/nginx/ssl
    environment:
      - PORT=8888
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME:-localhost}
    restart: unless-stopped 