version: '3.8'

services:
  qiankun-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-80}:${PORT:-80}"
    volumes:
      - ./ssl:/etc/nginx/ssl
    environment:
      - PORT=${PORT:-80}
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME:-localhost}
    restart: unless-stopped 